### ISSUE TITLE
Aktualizacja persistance/entity/*.Entity.java

### ISSUE THREAD

**Issue by j-dobrzanski** [progzesp22/StalkingGame#14]
Protokól w wersji 1.04 (i późniejsze) określa pola i ich nazwy dla obiektów typu tasks i answers - należy zadbać o zgodność kodu z obecną wersją protokołu - zaktualizować obecne nazwy pól gdy zgadza się ich funkcjonalność, usunąć pola obecnie nieużywane lub dodać nowe.

**Comment by Gemi0** [comment]
Należy również pamiętać o zmianach w ETO i mapperach

**Comment by Mkanobi** [comment]
Scommitowałem do brancha answers zmiany w TaskEto, TaskEntity, TaskMapper, żeby POST /tasks zgadzał się z protokołem.

**Comment by Mkanobi** [comment]
Pola obiektów tasks i answers są zgodne z wersją protokołu 1.05.
branch: database_update, 
commit: https://github.com/progzesp22/StalkingGame/commit/19db65de5c2b062b33f8bbb92f024caed9c17f5d
