### ISSUE TITLE
Wdrożenia obsługi sesji użytkownika

### ISSUE THREAD

**Issue by j-dobrzanski** [progzesp22/StalkingGame#15]
Należy przeprowadzić spotkanie z dyskusją (np. w stylu "burza mózgów") na temat sposobu tworzenia sessionTokenów oraz zaplanować wdrożenie tej funkcjonalności do obecnego już kodu; tj. rozpisać poszczególne zadania, a także zaktualizować dokumentację na ten temat i przekazać informacje o aktualizacji zespołowi frontendowemu.

**Comment by krzysztof9nowak** [comment]
Rozwiązanie znalezione przez Dominika wygląda ok:
https://youtu.be/VVn9OG9nfH0

Cele:
- stworzenie kilku demonstracyjnych kont
- umożliwienie logowania przez POST /user/login. W miarę możliwości zgodnie z proto.md, poinformowanie o koniecznych korektach
- zapisywanie GMa przy tworzeniu nowej gry przez POST /game
- ograniczenie dostępu do POST /tasks, do GMa danej gry

Termin: 20.11.2022
